### ISSUE TITLE
if your malloc failed - you still going to the while and trying to read input to it

### ISSUE THREAD

**Issue by meni181818** [ElchiYos/final-project#10]
https://github.com/ElchiYos/final-project/blob/83350b527a939a9e9bc655d784ebd5a25b8c8fc0/final%20project/main.c#L48
here:
https://github.com/ElchiYos/final-project/blob/83350b527a939a9e9bc655d784ebd5a25b8c8fc0/final%20project/main.c#L56

**Comment by ElchiYos** [comment]
fixed
