### ISSUE TITLE
unnecessary void pointer 

### ISSUE THREAD

**Issue by meni181818** [ElchiYos/final-project#6]
https://github.com/ElchiYos/final-project/blob/83350b527a939a9e9bc655d784ebd5a25b8c8fc0/final%20project/main.c#L8
if you always send `char *` why to use `void *` ?

**Comment by ElchiYos** [comment]
I made a generic function that receives void* and this is one of the specific functions (in "compareDebt" it receives a "float", and in "compareDates" it receives a "struct Date")

**Comment by ElchiYos** [comment]
I made a generic function that accepts void* and this is one of the specific functions (in compareDebt it receives a float, and in compareDates it receives a struct Date)

**Comment by meni181818** [comment]
can you show me where you use these functions?

**Comment by ElchiYos** [comment]
in this function
https://github.com/ElchiYos/final-project/blob/1a04fd1e2ffff8e65b67581f27a58f10d43ee7f5/final%20project/func.c#L216
I send according to the user's choice specific function to this function 
https://github.com/ElchiYos/final-project/blob/1a04fd1e2ffff8e65b67581f27a58f10d43ee7f5/final%20project/func.c#L303
which has a pointer to the function in the parameters
So if the user chooses to search by first name I send the function
https://github.com/ElchiYos/final-project/blob/1a04fd1e2ffff8e65b67581f27a58f10d43ee7f5/final%20project/main.c#L8
And if according to the date I send this function
https://github.com/ElchiYos/final-project/blob/1a04fd1e2ffff8e65b67581f27a58f10d43ee7f5/final%20project/main.c#L30

**Comment by meni181818** [comment]
thats actually really nice!
but contains a few problems.
1. your comparison functions signiture is not `int(*compare)(void*, void*)` but `(struct client* node, void* var2)`. (i really cant belive your compiller dosn't complains about that).
2. if you will declere the comparison functions as `(void*, void*)` then you will be able to send a direct pointer to the value without the pointer to th sturct itself.

**Comment by ElchiYos** [comment]
1. The compiler didn't complain about it apparently at all it did an implicit casting
2. Since I'm checking the whole list it works out better to send the structure and not the string
