### ISSUE TITLE
why not subtracting one from the other and return the result?

### ISSUE THREAD

**Issue by meni181818** [ElchiYos/final-project#8]
https://github.com/ElchiYos/final-project/blob/83350b527a939a9e9bc655d784ebd5a25b8c8fc0/final%20project/main.c#L24

**Comment by ElchiYos** [comment]
Since the function returns "int", then if the the debt difference is less than 1 and greater than 0, it will return 0. even though it's not equal.

**Comment by meni181818** [comment]
yes actually you right. but there is still a way to write it in one line..
