### ISSUE TITLE
you don't need to use dynamic allocation for that

### ISSUE THREAD

**Issue by meni181818** [ElchiYos/final-project#9]
https://github.com/ElchiYos/final-project/blob/83350b527a939a9e9bc655d784ebd5a25b8c8fc0/final%20project/main.c#L47
use dynamic allocation for one of the following:
1. you don't know the length at compile time but only in run time.
2. you want to free the memory before the stack get freed at the end of the scope.

**Comment by ElchiYos** [comment]
In the `oneQuerie` function I use `nameOfFile` to write to the file, so I need the default name and the name the user enters to be in the same variable

**Comment by ElchiYos** [comment]
fixed
